### ISSUE TITLE
Setting machine name from configuration screen causes uncaught exception

### ISSUE THREAD

**Issue by kyle-kingsbury** [FabMo/FabMo-Engine#1021]

**Comment by kyle-kingsbury** [comment]
Originally I thought this was a regression, but it persists back to at least v3.1.38. The machine name does change, but this exception is reported:

UNCAUGHT EXCEPTION
TypeError: Cannot read properties of undefined (reading 'once')
    at Engine.<anonymous> (/fabmo/engine.js:645:33)
    at EngineConfig.emit (node:events:520:28)
    at EngineConfig.<anonymous> (/fabmo/config/config.js:110:8)
    at /fabmo/config/engine_config.js:63:39
    at EngineConfig.<anonymous> (/fabmo/config/config.js:197:8)
    at FSReqCallback.oncomplete (node:fs:188:23)

**Comment by kyle-kingsbury** [comment]
Fixed as of v3.1.76
