### ISSUE TITLE
Triggering a "stop" input while manually jogging the machine

### ISSUE THREAD

**Issue by kyle-kingsbury** [FabMo/FabMo-Engine#1045]
Do what the title says, the "stop input activated" modal pops up, you cannot resume, but you can quit. Then if you try to enter the manual keypad again you get this error in the log

info: CODE!! [manual]
info: {"cmd":"enter"} [manual]
error: Error: Cannot create a new cycle context.  One already exists.
at G2._createCycleContext (/fabmo/g2.js:199:15)
at G2.runStream (/fabmo/g2.js:1059:10)
at ManualRuntime.enter (/fabmo/runtime/manual/index.js:70:17)
at ManualRuntime.executeCode (/fabmo/runtime/manual/index.js:114:18)
at Machine._executeRuntimeCode (/fabmo/machine.js:1370:34)
at Machine.fire (/fabmo/machine.js:780:18)
at Machine.arm (/fabmo/machine.js:710:18)
at Machine.executeRuntimeCode (/fabmo/machine.js:1318:18)
at Socket.<anonymous> (/fabmo/routes/websocket.js:154:25)
at Socket.emit (node:events:520:28) [websocket]

**Comment by kyle-kingsbury** [comment]
Fixed as of v3.1.76
