### ISSUE TITLE
Error when changing configurations for transforms on config page

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#162]
This example was generated when changing the rotation angle:

C:\Users\gordon\Documents\GitHub\FabMo-Engine\util.js:343
        var value = Number(json[key]);
                    ^
TypeError: Cannot convert object to primitive value
    at Number (<anonymous>)
    at Object.fixJSON (C:\Users\gordon\Documents\GitHub\FabMo-Engine\util.js:343:21)
    at Server.post_config (C:\Users\gordon\Documents\GitHub\FabMo-Engine\routes\config.js:111:32)
    at next (C:\Users\gordon\Documents\GitHub\FabMo-Engine\node_modules\restify\lib\server.js:906:30)
    at f (C:\Users\gordon\Documents\GitHub\FabMo-Engine\node_modules\restify\node_modules\once\once.js:17:25)
    at parseUrlEncodedBody (C:\Users\gordon\Documents\GitHub\FabMo-Engine\node_modules\restify\lib\plugins\form_body_parser.js:68:9)
    at Server.parseBody (C:\Users\gordon\Documents\GitHub\FabMo-Engine\node_modules\restify\lib\plugins\body_parser.js:90:13)
    at next (C:\Users\gordon\Documents\GitHub\FabMo-Engine\node_modules\restify\lib\server.js:906:30)
    at f (C:\Users\gordon\Documents\GitHub\FabMo-Engine\node_modules\restify\node_modules\once\once.js:17:25)
    at IncomingMessage.done (C:\Users\gordon\Documents\GitHub\FabMo-Engine\node_modules\restify\lib\plugins\body_reader.js:108:13)

**Comment by ryansturmer** [comment]
Fixed in a1bacb9a9580311cebe9f734f854f1fd387a2c01
