### ISSUE TITLE
Updated to 1.2.5, /dev/ttyACM1 missing

### ISSUE THREAD

**Issue by blandman** [FabMo/FabMo-Engine#532]
I am unsure if this is related to the update in general, or if this might be a hardware issue.

I have these devices under /dev/tty*

ttyACM0  ttyPTI0  
ttyGS0   ttyPTI1  
ttyMFD0  ttymcu0  
ttyMFD1  ttymcu1  
ttyMFD2 ttymcu2

I've tried several different combinations, none respond when running the engine and cause it to crash. Same result when using ttyACM0 for both data and control.
This handibot is running from factory hardware, Intel Edison.
Any insight would be appreciated.

**Comment by blandman** [comment]
Here's what I get when running `npm start`

```
info: Connecting to G2... [engine]
info: Opening control port /dev/ttyACM0 [g2]
info: Dual USB since control port and gcode port are different. (/dev/ttyACM0,/dev/ttyACM1) [g2]
error: ERROR OPENING CONTROL PORT Error: Cannot open /dev/ttyACM0 [g2]
warn: Setting the disconnected state [machine]
info: Got a machine state change: dead [machine]
error: G2 is dead! [machine]
error: !!!!!!!!!!!!!!!!!!!!!!!! [engine]
error: Could not connect to G2. [engine]
error: (Error: No connection to G2) [engine]
error: !!!!!!!!!!!!!!!!!!!!!!!! [engine]
info: Launching detection daemon... [engine]
info: Loading the machine configuration... [engine]
info: Setting driver units to INCH [g2]
UNCAUGHT EXCEPTION
Error: G2 is not responding
    at Watchdog.watchdog_exit [as _onTimeout] (/fabmo/engine/util.js:372:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

```

**Comment by blandman** [comment]
Handibot support gave me a firmware update file for the G2, this did the trick!
