### ISSUE TITLE
Unexplained crash in OpenSBP runtime

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#656]
```
May 04 14:01:05 shopbot-swole node[277]: debug: _executeNext called. [sbp]
May 04 14:01:05 shopbot-swole node[277]: debug: Stack break: {"type":"assign","var":"&npos","expr":"%(1)"} [sbp]
May 04 14:01:05 shopbot-swole node[277]: info: Priming driver (manually) [g2]
May 04 14:01:05 shopbot-swole node[277]: debug: Deferring because g-codes pending. [sbp]
May 04 14:01:05 shopbot-swole node[277]: g2: --S-1525442465205----> {"sr":null} [g2]
May 04 14:01:05 shopbot-swole node[277]: g2: <-S-1525442465208----- {"r":{"xjm":50},"f":[1,0,12]} [g2]
May 04 14:01:05 shopbot-swole node[277]: g2: <-S-1525442465211----- {"r":{"yjm":50},"f":[1,0,12]} [g2]
May 04 14:01:05 shopbot-swole node[277]: g2: <-S-1525442465212----- {"r":{"n":36},"f":[1,0,12]} [g2]
May 04 14:01:05 shopbot-swole node[277]: g2: <-S-1525442465215----- {"r":{"sr":{"posx":-0.99892,"posy":0,"posz":1,"posa":0,"posb":0,"vel":0,"stat":5,"hold":0,"line":36,"coor":2,"unit":0,"in1":1,"in2":0,"in3":1,"in4":0,"in5":0,"in6":0,"in7":0,"in8":0,"out1":0,"out2":0,"out3":0,"out4":1,"out5":0,"out6":0,"out7":0,"out8":0}},"f":[1,0,13]} [g2]
May 04 14:01:05 shopbot-swole node[277]: info: Got a machine state change: running [machine]
May 04 14:01:05 shopbot-swole node[277]: g2: <-S-1525442465452----- {"sr":{"stat":3,"line":36}} [g2]
May 04 14:01:05 shopbot-swole node[277]: debug: _executeNext called. [sbp]
May 04 14:01:05 shopbot-swole node[277]: debug: Stack break: {"type":"assign","var":"&npos","expr":"%(1)"} [sbp]
May 04 14:01:05 shopbot-swole node[277]: info: Priming driver (manually) [g2]
May 04 14:01:05 shopbot-swole node[277]: debug: executing: {"type":"assign","var":"&npos","expr":"%(1)"} [sbp]
May 04 14:01:05 shopbot-swole node[277]: debug: _executeNext called. [sbp]
May 04 14:01:05 shopbot-swole node[277]: debug: Stack break: {"type":"cond","cmp":{"left":"&npos","right":{"left":"&pos","right":0.002,"op":"-"},"op":"<"},"stmt":{"type":"goto","label":"exitThis"}} [sbp]
May 04 14:01:05 shopbot-swole node[277]: info: Priming driver (manually) [g2]
May 04 14:01:05 shopbot-swole node[277]: debug: executing: {"type":"cond","cmp":{"left":"&npos","right":{"left":"&pos","right":0.002,"op":"-"},"op":"<"},"stmt":{"type":"goto","label":"exitThis"}} [sbp]
May 04 14:01:05 shopbot-swole node[277]: debug: _executeNext called. [sbp]
May 04 14:01:05 shopbot-swole node[277]: debug: Stack break: {"type":"cond","cmp":{"left":"&npos","right":{"left":"&pos","right":0.002,"op":"+"},"op":">"},"stmt":{"type":"goto","label":"exitThis2"}} [sbp]
May 04 14:01:05 shopbot-swole node[277]: info: Priming driver (manually) [g2]
May 04 14:01:05 shopbot-swole node[277]: debug: executing: {"type":"cond","cmp":{"left":"&npos","right":{"left":"&pos","right":0.002,"op":"+"},"op":">"},"stmt":{"type":"goto","label":"exitThis2"}} [sbp]
May 04 14:01:05 shopbot-swole node[277]: debug: _executeNext called. [sbp]
May 04 14:01:05 shopbot-swole node[277]: debug: Stack break: {"type":"return"} [sbp]
May 04 14:01:05 shopbot-swole node[277]: info: Priming driver (manually) [g2]
May 04 14:01:05 shopbot-swole node[277]: debug: executing: {"type":"return"} [sbp]
May 04 14:01:05 shopbot-swole node[277]: debug: _executeNext called. [sbp]
May 04 14:01:05 shopbot-swole node[277]: UNCAUGHT EXCEPTION
May 04 14:01:05 shopbot-swole node[277]: TypeError: Cannot read property 'args' of undefined
May 04 14:01:05 shopbot-swole node[277]: at SBPRuntime._breaksStack (/fabmo/engine/runtime/opensbp/opensbp.js:435:8)
May 04 14:01:05 shopbot-swole node[277]: at SBPRuntime._executeNext (/fabmo/engine/runtime/opensbp/opensbp.js:623:28)
May 04 14:01:05 shopbot-swole node[277]: at processImmediate [as _immediateCallback] (timers.js:363:15)
May 04 14:01:05 shopbot-swole node[277]: info: Saving log... [log]
May 04 14:01:05 shopbot-swole node[277]: info: Log saved to /opt/fabmo/log/fabmo-1525442465482-log.txt [log]
May 04 14:01:08 shopbot-swole node[277]: g2: <-S-1525442468043----- {"sr":{"stat":3}} [g2]
May 04 14:06:50 shopbot-swole node[277]: debug: Client disconnected [websocket]
May 04 14:06:50 shopbot-swole node[277]: debug: Client disconnected [websocket]
May 04 14:06:50 shopbot-swole node[277]: info: Anonymous client at 192.168.33.124 connected. [websocket]
May 04 14:06:50 shopbot-swole node[277]: error: Error: No session provided.
May 04 14:06:50 shopbot-swole node[277]: at Array.0 (/fabmo/engine/routes/websocket.js:25:14)
May 04 14:06:50 shopbot-swole node[277]: at run (/fabmo/engine/node_modules/socket.io/lib/namespace.js:114:11)
May 04 14:06:50 shopbot-swole node[277]: at Namespace.run (/fabmo/engine/node_modules/socket.io/lib/namespace.js:126:3)
May 04 14:06:50 shopbot-swole node[277]: at Namespace.add (/fabmo/engine/node_modules/socket.io/lib/namespace.js:155:8)
May 04 14:06:50 shopbot-swole node[277]: at Client.connect (/fabmo/engine/node_modules/socket.io/lib/client.js:74:20)
May 04 14:06:50 shopbot-swole node[277]: at Client.ondecoded (/fabmo/engine/node_modules/socket.io/lib/client.js:189:10)
May 04 14:06:50 shopbot-swole node[277]: at Decoder.Emitter.emit (/fabmo/engine/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
May 04 14:06:50 shopbot-swole node[277]: at Decoder.add (/fabmo/engine/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
May 04 14:06:50 shopbot-swole node[277]: at Client.ondata (/fabmo/engine/node_modules/socket.io/lib/client.js:175:18)
May 04 14:06:50 shopbot-swole node[277]: at Socket.emit (events.js:95:17) [websocket]
May 04 14:06:50 shopbot-swole node[277]: { io: 'R44X63NU85fC-fDlAAAI' }
May 04 14:06:50 shopbot-swole node[277]: { [Error: ENOENT, stat 'dashboard/build/authentication/logout']
May 04 14:06:50 shopbot-swole node[277]: errno: 34,
May 04 14:06:50 shopbot-swole node[277]: code: 'ENOENT',
```

**Comment by ryansturmer** [comment]
This turned out to be a race condition in the command parser.
